version: '3'
services:
  drf:
    build: .
    container_name: django
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/usr/src/app
    ports:
      - "8000:8000"
    depends_on:
       - pgdb
    env_file:
       - ../.env
  pgdb:
    image: postgres
    container_name: pgdb
    env_file:
     - ../.env
    volumes:
     - pgdbdata:/var/lib/postgresql/data/


volumes:
  pgdbdata: null
