# Generated by Django 4.1 on 2022-09-04 11:37

import comments.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='user_photo',
            field=models.ImageField(blank=True, null=True, upload_to=comments.models.upload_location),
        ),
    ]
