# Generated by Django 4.1 on 2022-09-05 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0002_alter_usermodel_user_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='photo_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
