# Generated by Django 4.1 on 2022-09-05 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0003_usermodel_photo_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermodel',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='usermodel',
            name='username',
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='photo_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
