# Generated by Django 4.1 on 2022-09-05 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0005_alter_usermodel_photo_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermodel',
            name='user_id',
        ),
    ]
