# Generated by Django 4.1 on 2022-09-05 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0007_usermodel_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermodel',
            name='user_id',
        ),
    ]
