# Generated by Django 4.1 on 2022-09-05 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0008_remove_usermodel_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='user_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
