# Generated by Django 4.1 on 2022-09-06 16:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0010_jobmodel_ratingermodel_remove_usermodel_user_photo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DirectionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='ratingermodel',
            name='language',
            field=models.TextField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='direction',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='staff', to='comments.directionmodel'),
            preserve_default=False,
        ),
    ]
