# Generated by Django 4.1 on 2022-09-07 08:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0011_directionmodel_alter_ratingermodel_language_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermodel',
            name='direction',
        ),
        migrations.AddField(
            model_name='jobmodel',
            name='direction',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='staff', to='comments.directionmodel'),
            preserve_default=False,
        ),
    ]
