# Generated by Django 4.1 on 2022-09-08 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0012_remove_usermodel_direction_jobmodel_direction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ratingermodel',
            name='language',
            field=models.TextField(blank=True, default='ru', max_length=2, null=True),
        ),
    ]
