# Generated by Django 4.1 on 2022-09-09 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0013_alter_ratingermodel_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='photo_id',
            field=models.TextField(blank=True, default='AgACAgIAAxkBAAIKR2MauaF0hSSG1-dy9mY9I1XvxvWhAALUvjEbkZjRSDADYKmMGabgAQADAgADeQADKQQ', null=True),
        ),
    ]
