# Generated by Django 4.1 on 2022-10-10 11:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0016_ratingmodel_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='date',
            field=models.DateField(default=datetime.datetime.today),
        ),
    ]
